### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by llorllale** [llorllale/go-gitlint#16]
Let's add filters to detect violations on commit subjects and bodies by using regular expressions.

**Comment by 0pdd** [comment]
@llorllale the puzzle [#18](https://github.com/llorllale/go-gitlint/issues/18) is still not solved.

**Comment by llorllale** [comment]
Merged in #17

**Comment by 0pdd** [comment]
@llorllale the only puzzle [#18](https://github.com/llorllale/go-gitlint/issues/18) is solved here.
