### ISSUE TITLE
--since=<date> Filter

### ISSUE THREAD

**Issue by llorllale** [llorllale/go-gitlint#31]

**Comment by 0pdd** [comment]
@llorllale the puzzle [#34](https://github.com/llorllale/go-gitlint/issues/34) is still not solved.

**Comment by llorllale** [comment]
Merged in #33

**Comment by 0pdd** [comment]
@llorllale the only puzzle [#34](https://github.com/llorllale/go-gitlint/issues/34) is solved here.
