### ISSUE TITLE
Ignore user from gitlint

### ISSUE THREAD

**Issue by paulodamaso** [llorllale/go-gitlint#52]
We should be able to ignore users from gitlink, to avoid problems when `ARC` or even rultor needs make a commit to repository.

**Comment by llorllale** [comment]
@paulodamaso I think this just encourages bad practices from the ARC and PO. I had previously warned Yegor against this - see yegor256/cactoos#1148

Nevertheless I'll look into this and will let you know.

**Comment by paulodamaso** [comment]
@llorllale I agree. But i'm having a great problem in cactoos due the commit that puts me as architect: the commit does not follow lint rules, but it was merged anyways. Fact is, we can't stop ARC, PO and whoever who has write permission to a repository to make direct commits. And these commits are messing with future commits. I think these rules should be enforced BEFORE the commit enters the repo, and not after, as it does checking the commit logs.

One way to avoid all this problems could be to do not check ARC and PO commits, specially because sometimes these roles can be tempted to make commmits for quick fixes.

**Comment by llorllale** [comment]
@paulodamaso do you wish to match by the author's name or their email? Are you looking for exact matches or would you rather match against patterns?

**Comment by llorllale** [comment]
@paulodamaso 

> One way to avoid all this problems could be to do not check ARC and PO commits, specially because sometimes these roles can be tempted to make commmits for quick fixes.

Another way is to make the master branch read-only. Yegor's words: https://www.yegor256.com/2014/07/21/read-only-master-branch.html. This is a simple configuration in the project's settings - all it takes is a click on a checkbox. Enforcing these rules *before* merging to `master` is then a simple matter of raising a PR.

But if some people don't wish to follow procedure... `¯\_(ツ)_/¯`

**Comment by llorllale** [comment]
@paulodamaso I released [`1.1.0`](https://github.com/llorllale/go-gitlint/releases/tag/1.1.0) with two new flags `excl-author-names` and `excl-author-emails`. Both are comma-separated lists of regular expressions that you can use to exclude authors by name or email.

Let me know.

**Comment by paulodamaso** [comment]
@llorllale thank you very much, I'll make some tests and tell you

**Comment by llorllale** [comment]
@paulodamaso closing this - please open a new issue in the future for any followup
